name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'New Features'
    labels: ['enhancement']
  - title: 'Bug Fixes'
    labels: ['bug']
  - title: 'Documentation'
    labels: ['documentation']
  - title: 'Testing'
    labels: ['testing']
  - title: 'Infrastructure'
    labels: ['ci', 'infra']
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor', 'enhancement']
  patch:
    labels: ['patch', 'bug', 'documentation']
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
