#!/usr/bin/env python3
"""Generate docs/tools/reference.md from the live MCP server.

Introspects the registered FastMCP tools (name, description, parameters) and
writes a full reference. Run it after adding/changing a tool so the docs never
drift from the code (a test enforces coverage):

    python scripts/gen_tool_reference.py
"""

from __future__ import annotations

import asyncio
import pathlib
from typing import Any

_REF = pathlib.Path(__file__).resolve().parents[1] / "docs" / "tools" / "reference.md"


def _type_str(info: dict[str, Any]) -> str:
    if "type" in info:
        return str(info["type"])
    if "anyOf" in info:
        parts = [a.get("type", "any") for a in info["anyOf"] if a.get("type") != "null"]
        opt = " | null" if any(a.get("type") == "null" for a in info["anyOf"]) else ""
        return (" | ".join(parts) or "any") + opt
    return "any"


def _params_from_schema(schema: dict[str, Any] | None) -> list[dict[str, Any]]:
    schema = schema or {}
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    params = []
    for name, info in props.items():
        params.append(
            {
                "name": name,
                "type": _type_str(info),
                "required": name in required,
                "default": info.get("default"),
                "description": (info.get("description") or "").strip(),
            }
        )
    return params


async def collect_tools() -> list[dict[str, Any]]:
    """Return [{name, description, params}] for every registered MCP tool."""
    from fastmcp import Client

    from viznoir.server import mcp

    out = []
    async with Client(mcp) as client:
        for tool in await client.list_tools():
            out.append(
                {
                    "name": tool.name,
                    "description": (tool.description or "").strip(),
                    "params": _params_from_schema(tool.inputSchema),
                }
            )
    return sorted(out, key=lambda t: t["name"])


def render_markdown(tools: list[dict[str, Any]]) -> str:
    lines = [
        "# Tool Reference",
        "",
        "<!-- AUTO-GENERATED by scripts/gen_tool_reference.py — do not edit by hand. -->",
        "",
        f"viznoir exposes **{len(tools)} MCP tools**. Each renders or analyses simulation "
        "data and returns a PNG/glTF artifact or structured JSON.",
        "",
    ]
    for tool in tools:
        lines.append(f"## `{tool['name']}`")
        lines.append("")
        desc = tool["description"].split("\n\n")[0].strip() if tool["description"] else ""
        if desc:
            lines.append(desc)
            lines.append("")
        if tool["params"]:
            lines.append("| Parameter | Type | Required | Default | Description |")
            lines.append("|-----------|------|----------|---------|-------------|")
            for p in tool["params"]:
                dflt = p.get("default")
                default = "" if dflt is None else f"`{dflt}`"
                req = "yes" if p.get("required") else ""
                ptype = str(p.get("type", "any")).replace("|", "\\|")  # keep table intact
                pdesc = (p.get("description") or "").split("\n")[0][:80].replace("|", "\\|")
                lines.append(f"| `{p['name']}` | {ptype} | {req} | {default} | {pdesc} |")
            lines.append("")
        else:
            lines.append("_No parameters._")
            lines.append("")
    return "\n".join(lines)


async def main() -> None:
    tools = await collect_tools()
    _REF.parent.mkdir(parents=True, exist_ok=True)
    _REF.write_text(render_markdown(tools))
    print(f"wrote {_REF} ({len(tools)} tools)")


if __name__ == "__main__":
    asyncio.run(main())
